global:
  database_path: ../development_datas/database.db
  datawarehouse_path: ../development_datas/
  templates_path: ./templates/
  external_resources_path: ./external

orchestrator:
  max_parallel_instances: 4
  timeout_seconds: 900

performance_analyzer:
  metrics:
    - accuracy
    - over_detection_count_per_hour
  visualization_level: standard

instance_analyzer:
  max_hypothesis_attempts: 3
  llm_model: gpt-4
  temperature: 0.1
  require_llm: true
  drowsy_detection:
    left_eye_close_threshold: 0.10
    right_eye_close_threshold: 0.10
    continuous_close_time: 1.00
    face_conf_threshold: 0.75
  resources:
    external_root: ./external
    algorithm:
      spec_dirs:
        - drowsy_detection/01_algorithm_specification
        - drowsy_detection/02_specific_design
      code_dirs:
        - drowsy_detection/src/drowsy_detection
      extra_files: []
    evaluation:
      spec_dirs:
        - drowsy_detection/evaluation_engine
      code_dirs:
        - drowsy_detection/evaluation_engine
      extra_files: []
